// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: acceptances.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAcceptanceEvent = `-- name: CreateAcceptanceEvent :one
INSERT INTO acceptance_events (
  subject_ref,
  document_version_id,
  accepted_at,
  source_service,
  source_app,
  ip_address,
  user_agent,
  evidence_sha256,
  metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, subject_ref, document_version_id, accepted_at, source_service, source_app, ip_address, user_agent, evidence_sha256, metadata, created_at
`

type CreateAcceptanceEventParams struct {
	SubjectRef        string             `json:"subject_ref"`
	DocumentVersionID string             `json:"document_version_id"`
	AcceptedAt        pgtype.Timestamptz `json:"accepted_at"`
	SourceService     string             `json:"source_service"`
	SourceApp         string             `json:"source_app"`
	IpAddress         string             `json:"ip_address"`
	UserAgent         string             `json:"user_agent"`
	EvidenceSha256    string             `json:"evidence_sha256"`
	Metadata          []byte             `json:"metadata"`
}

func (q *Queries) CreateAcceptanceEvent(ctx context.Context, arg CreateAcceptanceEventParams) (AcceptanceEvent, error) {
	row := q.db.QueryRow(ctx, createAcceptanceEvent,
		arg.SubjectRef,
		arg.DocumentVersionID,
		arg.AcceptedAt,
		arg.SourceService,
		arg.SourceApp,
		arg.IpAddress,
		arg.UserAgent,
		arg.EvidenceSha256,
		arg.Metadata,
	)
	var i AcceptanceEvent
	err := row.Scan(
		&i.ID,
		&i.SubjectRef,
		&i.DocumentVersionID,
		&i.AcceptedAt,
		&i.SourceService,
		&i.SourceApp,
		&i.IpAddress,
		&i.UserAgent,
		&i.EvidenceSha256,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAcceptanceEventsBySubject = `-- name: ListAcceptanceEventsBySubject :many
SELECT
  ae.id,
  ae.subject_ref,
  ae.accepted_at,
  ae.source_service,
  ae.source_app,
  ae.ip_address,
  ae.user_agent,
  ae.evidence_sha256,
  ae.metadata,
  ae.created_at,
  d.key AS document_key,
  d.display_name,
  d.category,
  dv.version AS document_version,
  dv.locale,
  dv.audience,
  dv.content_type,
  dv.content_sha256
FROM acceptance_events ae
JOIN document_versions dv ON dv.id = ae.document_version_id
JOIN documents d ON d.id = dv.document_id
WHERE ae.subject_ref = $1
ORDER BY ae.accepted_at DESC, ae.created_at DESC
`

type ListAcceptanceEventsBySubjectRow struct {
	ID              string             `json:"id"`
	SubjectRef      string             `json:"subject_ref"`
	AcceptedAt      pgtype.Timestamptz `json:"accepted_at"`
	SourceService   string             `json:"source_service"`
	SourceApp       string             `json:"source_app"`
	IpAddress       string             `json:"ip_address"`
	UserAgent       string             `json:"user_agent"`
	EvidenceSha256  string             `json:"evidence_sha256"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	DocumentKey     string             `json:"document_key"`
	DisplayName     string             `json:"display_name"`
	Category        string             `json:"category"`
	DocumentVersion string             `json:"document_version"`
	Locale          string             `json:"locale"`
	Audience        string             `json:"audience"`
	ContentType     string             `json:"content_type"`
	ContentSha256   string             `json:"content_sha256"`
}

func (q *Queries) ListAcceptanceEventsBySubject(ctx context.Context, subjectRef string) ([]ListAcceptanceEventsBySubjectRow, error) {
	rows, err := q.db.Query(ctx, listAcceptanceEventsBySubject, subjectRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAcceptanceEventsBySubjectRow
	for rows.Next() {
		var i ListAcceptanceEventsBySubjectRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectRef,
			&i.AcceptedAt,
			&i.SourceService,
			&i.SourceApp,
			&i.IpAddress,
			&i.UserAgent,
			&i.EvidenceSha256,
			&i.Metadata,
			&i.CreatedAt,
			&i.DocumentKey,
			&i.DisplayName,
			&i.Category,
			&i.DocumentVersion,
			&i.Locale,
			&i.Audience,
			&i.ContentType,
			&i.ContentSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
