// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consents.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConsentEvent = `-- name: CreateConsentEvent :one
INSERT INTO consent_events (
  subject_ref,
  consent_purpose_id,
  document_version_id,
  status,
  legal_basis,
  changed_at,
  source_service,
  source_app,
  evidence_sha256,
  metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, subject_ref, consent_purpose_id, document_version_id, status, legal_basis, changed_at, source_service, source_app, evidence_sha256, metadata, created_at
`

type CreateConsentEventParams struct {
	SubjectRef        string             `json:"subject_ref"`
	ConsentPurposeID  string             `json:"consent_purpose_id"`
	DocumentVersionID string             `json:"document_version_id"`
	Status            string             `json:"status"`
	LegalBasis        string             `json:"legal_basis"`
	ChangedAt         pgtype.Timestamptz `json:"changed_at"`
	SourceService     string             `json:"source_service"`
	SourceApp         string             `json:"source_app"`
	EvidenceSha256    string             `json:"evidence_sha256"`
	Metadata          []byte             `json:"metadata"`
}

func (q *Queries) CreateConsentEvent(ctx context.Context, arg CreateConsentEventParams) (ConsentEvent, error) {
	row := q.db.QueryRow(ctx, createConsentEvent,
		arg.SubjectRef,
		arg.ConsentPurposeID,
		arg.DocumentVersionID,
		arg.Status,
		arg.LegalBasis,
		arg.ChangedAt,
		arg.SourceService,
		arg.SourceApp,
		arg.EvidenceSha256,
		arg.Metadata,
	)
	var i ConsentEvent
	err := row.Scan(
		&i.ID,
		&i.SubjectRef,
		&i.ConsentPurposeID,
		&i.DocumentVersionID,
		&i.Status,
		&i.LegalBasis,
		&i.ChangedAt,
		&i.SourceService,
		&i.SourceApp,
		&i.EvidenceSha256,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getConsentPurposeByKey = `-- name: GetConsentPurposeByKey :one
SELECT id, key, display_name, description, created_at
FROM consent_purposes
WHERE key = $1
`

func (q *Queries) GetConsentPurposeByKey(ctx context.Context, key string) (ConsentPurpose, error) {
	row := q.db.QueryRow(ctx, getConsentPurposeByKey, key)
	var i ConsentPurpose
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.DisplayName,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentConsentsBySubject = `-- name: GetCurrentConsentsBySubject :many
SELECT DISTINCT ON (cp.key)
  ce.id,
  ce.subject_ref,
  ce.status,
  ce.legal_basis,
  ce.changed_at,
  ce.source_service,
  ce.source_app,
  ce.evidence_sha256,
  ce.metadata,
  ce.created_at,
  cp.key AS purpose_key,
  cp.display_name AS purpose_display_name,
  cp.description AS purpose_description,
  d.key AS document_key,
  d.display_name,
  dv.version AS document_version,
  dv.locale,
  dv.audience
FROM consent_events ce
JOIN consent_purposes cp ON cp.id = ce.consent_purpose_id
JOIN document_versions dv ON dv.id = ce.document_version_id
JOIN documents d ON d.id = dv.document_id
WHERE ce.subject_ref = $1
ORDER BY cp.key, ce.changed_at DESC, ce.created_at DESC
`

type GetCurrentConsentsBySubjectRow struct {
	ID                 string             `json:"id"`
	SubjectRef         string             `json:"subject_ref"`
	Status             string             `json:"status"`
	LegalBasis         string             `json:"legal_basis"`
	ChangedAt          pgtype.Timestamptz `json:"changed_at"`
	SourceService      string             `json:"source_service"`
	SourceApp          string             `json:"source_app"`
	EvidenceSha256     string             `json:"evidence_sha256"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	PurposeKey         string             `json:"purpose_key"`
	PurposeDisplayName string             `json:"purpose_display_name"`
	PurposeDescription string             `json:"purpose_description"`
	DocumentKey        string             `json:"document_key"`
	DisplayName        string             `json:"display_name"`
	DocumentVersion    string             `json:"document_version"`
	Locale             string             `json:"locale"`
	Audience           string             `json:"audience"`
}

func (q *Queries) GetCurrentConsentsBySubject(ctx context.Context, subjectRef string) ([]GetCurrentConsentsBySubjectRow, error) {
	rows, err := q.db.Query(ctx, getCurrentConsentsBySubject, subjectRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCurrentConsentsBySubjectRow
	for rows.Next() {
		var i GetCurrentConsentsBySubjectRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectRef,
			&i.Status,
			&i.LegalBasis,
			&i.ChangedAt,
			&i.SourceService,
			&i.SourceApp,
			&i.EvidenceSha256,
			&i.Metadata,
			&i.CreatedAt,
			&i.PurposeKey,
			&i.PurposeDisplayName,
			&i.PurposeDescription,
			&i.DocumentKey,
			&i.DisplayName,
			&i.DocumentVersion,
			&i.Locale,
			&i.Audience,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsentEventsBySubject = `-- name: ListConsentEventsBySubject :many
SELECT
  ce.id,
  ce.subject_ref,
  ce.status,
  ce.legal_basis,
  ce.changed_at,
  ce.source_service,
  ce.source_app,
  ce.evidence_sha256,
  ce.metadata,
  ce.created_at,
  cp.key AS purpose_key,
  cp.display_name AS purpose_display_name,
  cp.description AS purpose_description,
  d.key AS document_key,
  d.display_name,
  dv.version AS document_version,
  dv.locale,
  dv.audience
FROM consent_events ce
JOIN consent_purposes cp ON cp.id = ce.consent_purpose_id
JOIN document_versions dv ON dv.id = ce.document_version_id
JOIN documents d ON d.id = dv.document_id
WHERE ce.subject_ref = $1
ORDER BY ce.changed_at DESC, ce.created_at DESC
`

type ListConsentEventsBySubjectRow struct {
	ID                 string             `json:"id"`
	SubjectRef         string             `json:"subject_ref"`
	Status             string             `json:"status"`
	LegalBasis         string             `json:"legal_basis"`
	ChangedAt          pgtype.Timestamptz `json:"changed_at"`
	SourceService      string             `json:"source_service"`
	SourceApp          string             `json:"source_app"`
	EvidenceSha256     string             `json:"evidence_sha256"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	PurposeKey         string             `json:"purpose_key"`
	PurposeDisplayName string             `json:"purpose_display_name"`
	PurposeDescription string             `json:"purpose_description"`
	DocumentKey        string             `json:"document_key"`
	DisplayName        string             `json:"display_name"`
	DocumentVersion    string             `json:"document_version"`
	Locale             string             `json:"locale"`
	Audience           string             `json:"audience"`
}

func (q *Queries) ListConsentEventsBySubject(ctx context.Context, subjectRef string) ([]ListConsentEventsBySubjectRow, error) {
	rows, err := q.db.Query(ctx, listConsentEventsBySubject, subjectRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConsentEventsBySubjectRow
	for rows.Next() {
		var i ListConsentEventsBySubjectRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectRef,
			&i.Status,
			&i.LegalBasis,
			&i.ChangedAt,
			&i.SourceService,
			&i.SourceApp,
			&i.EvidenceSha256,
			&i.Metadata,
			&i.CreatedAt,
			&i.PurposeKey,
			&i.PurposeDisplayName,
			&i.PurposeDescription,
			&i.DocumentKey,
			&i.DisplayName,
			&i.DocumentVersion,
			&i.Locale,
			&i.Audience,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConsentPurpose = `-- name: UpsertConsentPurpose :one
INSERT INTO consent_purposes (key, display_name, description)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE
SET display_name = EXCLUDED.display_name,
    description = EXCLUDED.description
RETURNING id, key, display_name, description, created_at
`

type UpsertConsentPurposeParams struct {
	Key         string `json:"key"`
	DisplayName string `json:"display_name"`
	Description string `json:"description"`
}

func (q *Queries) UpsertConsentPurpose(ctx context.Context, arg UpsertConsentPurposeParams) (ConsentPurpose, error) {
	row := q.db.QueryRow(ctx, upsertConsentPurpose, arg.Key, arg.DisplayName, arg.Description)
	var i ConsentPurpose
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.DisplayName,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
