// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (key, display_name, category)
VALUES ($1, $2, $3)
RETURNING id, key, display_name, category, created_at
`

type CreateDocumentParams struct {
	Key         string `json:"key"`
	DisplayName string `json:"display_name"`
	Category    string `json:"category"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument, arg.Key, arg.DisplayName, arg.Category)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.DisplayName,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const createDocumentVersion = `-- name: CreateDocumentVersion :one
INSERT INTO document_versions (
  document_id,
  version,
  locale,
  audience,
  content_type,
  content_text,
  content_sha256,
  is_published,
  effective_from,
  created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, document_id, version, locale, audience, content_type, content_text, content_sha256, is_published, effective_from, created_by, created_at
`

type CreateDocumentVersionParams struct {
	DocumentID    string             `json:"document_id"`
	Version       string             `json:"version"`
	Locale        string             `json:"locale"`
	Audience      string             `json:"audience"`
	ContentType   string             `json:"content_type"`
	ContentText   string             `json:"content_text"`
	ContentSha256 string             `json:"content_sha256"`
	IsPublished   bool               `json:"is_published"`
	EffectiveFrom pgtype.Timestamptz `json:"effective_from"`
	CreatedBy     string             `json:"created_by"`
}

func (q *Queries) CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, createDocumentVersion,
		arg.DocumentID,
		arg.Version,
		arg.Locale,
		arg.Audience,
		arg.ContentType,
		arg.ContentText,
		arg.ContentSha256,
		arg.IsPublished,
		arg.EffectiveFrom,
		arg.CreatedBy,
	)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Version,
		&i.Locale,
		&i.Audience,
		&i.ContentType,
		&i.ContentText,
		&i.ContentSha256,
		&i.IsPublished,
		&i.EffectiveFrom,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentByKey = `-- name: GetDocumentByKey :one
SELECT id, key, display_name, category, created_at
FROM documents
WHERE key = $1
LIMIT 1
`

func (q *Queries) GetDocumentByKey(ctx context.Context, key string) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByKey, key)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.DisplayName,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentVersionByNaturalKey = `-- name: GetDocumentVersionByNaturalKey :one
SELECT dv.id, dv.document_id, dv.version, dv.locale, dv.audience, dv.content_type, dv.content_text, dv.content_sha256, dv.is_published, dv.effective_from, dv.created_by, dv.created_at
FROM document_versions dv
JOIN documents d ON d.id = dv.document_id
WHERE d.key = $1
  AND dv.version = $2
  AND dv.locale = $3
  AND dv.audience = $4
LIMIT 1
`

type GetDocumentVersionByNaturalKeyParams struct {
	Key      string `json:"key"`
	Version  string `json:"version"`
	Locale   string `json:"locale"`
	Audience string `json:"audience"`
}

func (q *Queries) GetDocumentVersionByNaturalKey(ctx context.Context, arg GetDocumentVersionByNaturalKeyParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, getDocumentVersionByNaturalKey,
		arg.Key,
		arg.Version,
		arg.Locale,
		arg.Audience,
	)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Version,
		&i.Locale,
		&i.Audience,
		&i.ContentType,
		&i.ContentText,
		&i.ContentSha256,
		&i.IsPublished,
		&i.EffectiveFrom,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentVersionsByKey = `-- name: ListDocumentVersionsByKey :many
SELECT
  d.key AS document_key,
  d.display_name,
  dv.id,
  dv.version,
  dv.locale,
  dv.audience,
  dv.content_type,
  dv.is_published,
  dv.effective_from,
  dv.created_by,
  dv.created_at
FROM document_versions dv
JOIN documents d ON d.id = dv.document_id
WHERE d.key = $1
ORDER BY dv.effective_from DESC, dv.created_at DESC
`

type ListDocumentVersionsByKeyRow struct {
	DocumentKey  string             `json:"document_key"`
	DisplayName  string             `json:"display_name"`
	ID           int64              `json:"id"`
	Version      string             `json:"version"`
	Locale       string             `json:"locale"`
	Audience     string             `json:"audience"`
	ContentType  string             `json:"content_type"`
	IsPublished  bool               `json:"is_published"`
	EffectiveFrom pgtype.Timestamptz `json:"effective_from"`
	CreatedBy    string             `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDocumentVersionsByKey(ctx context.Context, key string) ([]ListDocumentVersionsByKeyRow, error) {
	rows, err := q.db.Query(ctx, listDocumentVersionsByKey, key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []ListDocumentVersionsByKeyRow
	for rows.Next() {
		var i ListDocumentVersionsByKeyRow
		if err := rows.Scan(
			&i.DocumentKey,
			&i.DisplayName,
			&i.ID,
			&i.Version,
			&i.Locale,
			&i.Audience,
			&i.ContentType,
			&i.IsPublished,
			&i.EffectiveFrom,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getLatestPublishedDocumentVersion = `-- name: GetLatestPublishedDocumentVersion :one
SELECT
  d.key AS document_key,
  d.display_name,
  d.category,
  dv.id,
  dv.version,
  dv.locale,
  dv.audience,
  dv.content_type,
  dv.content_text,
  dv.content_sha256,
  dv.is_published,
  dv.effective_from,
  dv.created_by,
  dv.created_at
FROM document_versions dv
JOIN documents d ON d.id = dv.document_id
WHERE d.key = $1
  AND dv.locale = $2
  AND dv.audience = $3
  AND dv.is_published = TRUE
  AND dv.effective_from <= NOW()
ORDER BY dv.effective_from DESC, dv.created_at DESC
LIMIT 1
`

type GetLatestPublishedDocumentVersionParams struct {
	Key      string `json:"key"`
	Locale   string `json:"locale"`
	Audience string `json:"audience"`
}

type GetLatestPublishedDocumentVersionRow struct {
	DocumentKey   string             `json:"document_key"`
	DisplayName   string             `json:"display_name"`
	Category      string             `json:"category"`
	ID            string             `json:"id"`
	Version       string             `json:"version"`
	Locale        string             `json:"locale"`
	Audience      string             `json:"audience"`
	ContentType   string             `json:"content_type"`
	ContentText   string             `json:"content_text"`
	ContentSha256 string             `json:"content_sha256"`
	IsPublished   bool               `json:"is_published"`
	EffectiveFrom pgtype.Timestamptz `json:"effective_from"`
	CreatedBy     string             `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetLatestPublishedDocumentVersion(ctx context.Context, arg GetLatestPublishedDocumentVersionParams) (GetLatestPublishedDocumentVersionRow, error) {
	row := q.db.QueryRow(ctx, getLatestPublishedDocumentVersion, arg.Key, arg.Locale, arg.Audience)
	var i GetLatestPublishedDocumentVersionRow
	err := row.Scan(
		&i.DocumentKey,
		&i.DisplayName,
		&i.Category,
		&i.ID,
		&i.Version,
		&i.Locale,
		&i.Audience,
		&i.ContentType,
		&i.ContentText,
		&i.ContentSha256,
		&i.IsPublished,
		&i.EffectiveFrom,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const upsertDocument = `-- name: UpsertDocument :one
INSERT INTO documents (key, display_name, category)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE
SET display_name = EXCLUDED.display_name,
    category = EXCLUDED.category
RETURNING id, key, display_name, category, created_at
`

type UpsertDocumentParams struct {
	Key         string `json:"key"`
	DisplayName string `json:"display_name"`
	Category    string `json:"category"`
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, upsertDocument, arg.Key, arg.DisplayName, arg.Category)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.DisplayName,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const upsertDocumentVersion = `-- name: UpsertDocumentVersion :one
INSERT INTO document_versions (
  document_id,
  version,
  locale,
  audience,
  content_type,
  content_text,
  content_sha256,
  is_published,
  effective_from,
  created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (document_id, version, locale, audience) DO UPDATE
SET content_type = EXCLUDED.content_type,
    content_text = EXCLUDED.content_text,
    content_sha256 = EXCLUDED.content_sha256,
    is_published = EXCLUDED.is_published,
    effective_from = EXCLUDED.effective_from,
    created_by = EXCLUDED.created_by
RETURNING id, document_id, version, locale, audience, content_type, content_text, content_sha256, is_published, effective_from, created_by, created_at
`

type UpsertDocumentVersionParams struct {
	DocumentID    string             `json:"document_id"`
	Version       string             `json:"version"`
	Locale        string             `json:"locale"`
	Audience      string             `json:"audience"`
	ContentType   string             `json:"content_type"`
	ContentText   string             `json:"content_text"`
	ContentSha256 string             `json:"content_sha256"`
	IsPublished   bool               `json:"is_published"`
	EffectiveFrom pgtype.Timestamptz `json:"effective_from"`
	CreatedBy     string             `json:"created_by"`
}

func (q *Queries) UpsertDocumentVersion(ctx context.Context, arg UpsertDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, upsertDocumentVersion,
		arg.DocumentID,
		arg.Version,
		arg.Locale,
		arg.Audience,
		arg.ContentType,
		arg.ContentText,
		arg.ContentSha256,
		arg.IsPublished,
		arg.EffectiveFrom,
		arg.CreatedBy,
	)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Version,
		&i.Locale,
		&i.Audience,
		&i.ContentType,
		&i.ContentText,
		&i.ContentSha256,
		&i.IsPublished,
		&i.EffectiveFrom,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
