// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: governance.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listDPIARecords = `-- name: ListDPIARecords :many
SELECT id, key, display_name, status, summary, scope, risk_level, mitigating_measures, owner, review_due_at, is_active, created_at, updated_at
FROM dpia_records
ORDER BY is_active DESC, status ASC, display_name ASC, created_at ASC
`

func (q *Queries) ListDPIARecords(ctx context.Context) ([]DpiaRecord, error) {
	rows, err := q.db.Query(ctx, listDPIARecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DpiaRecord
	for rows.Next() {
		var i DpiaRecord
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.DisplayName,
			&i.Status,
			&i.Summary,
			&i.Scope,
			&i.RiskLevel,
			&i.MitigatingMeasures,
			&i.Owner,
			&i.ReviewDueAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcessingActivities = `-- name: ListProcessingActivities :many
SELECT id, key, display_name, purpose, legal_basis, data_subject_categories, personal_data_categories, recipient_categories, transfer_notes, retention_summary, security_measures, owner, is_active, created_at, updated_at
FROM processing_activities
ORDER BY is_active DESC, display_name ASC, created_at ASC
`

func (q *Queries) ListProcessingActivities(ctx context.Context) ([]ProcessingActivity, error) {
	rows, err := q.db.Query(ctx, listProcessingActivities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProcessingActivity
	for rows.Next() {
		var i ProcessingActivity
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.DisplayName,
			&i.Purpose,
			&i.LegalBasis,
			&i.DataSubjectCategories,
			&i.PersonalDataCategories,
			&i.RecipientCategories,
			&i.TransferNotes,
			&i.RetentionSummary,
			&i.SecurityMeasures,
			&i.Owner,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcessors = `-- name: ListProcessors :many
SELECT id, key, display_name, relationship_type, service_area, website_url, primary_country, data_location, transfer_mechanism, dpa_status, notes, is_active, created_at, updated_at
FROM processors
ORDER BY is_active DESC, display_name ASC, created_at ASC
`

func (q *Queries) ListProcessors(ctx context.Context) ([]Processor, error) {
	rows, err := q.db.Query(ctx, listProcessors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Processor
	for rows.Next() {
		var i Processor
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.DisplayName,
			&i.RelationshipType,
			&i.ServiceArea,
			&i.WebsiteUrl,
			&i.PrimaryCountry,
			&i.DataLocation,
			&i.TransferMechanism,
			&i.DpaStatus,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetentionPolicies = `-- name: ListRetentionPolicies :many
SELECT id, key, display_name, data_category, description, retention_days, trigger_event, storage_scope, deletion_method, legal_basis, notes, is_active, created_at, updated_at
FROM retention_policies
ORDER BY is_active DESC, data_category ASC, display_name ASC, created_at ASC
`

func (q *Queries) ListRetentionPolicies(ctx context.Context) ([]RetentionPolicy, error) {
	rows, err := q.db.Query(ctx, listRetentionPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetentionPolicy
	for rows.Next() {
		var i RetentionPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.DisplayName,
			&i.DataCategory,
			&i.Description,
			&i.RetentionDays,
			&i.TriggerEvent,
			&i.StorageScope,
			&i.DeletionMethod,
			&i.LegalBasis,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDPIARecord = `-- name: UpsertDPIARecord :one
INSERT INTO dpia_records (
  key,
  display_name,
  status,
  summary,
  scope,
  risk_level,
  mitigating_measures,
  owner,
  review_due_at,
  is_active,
  updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW())
ON CONFLICT (key) DO UPDATE
SET display_name = EXCLUDED.display_name,
    status = EXCLUDED.status,
    summary = EXCLUDED.summary,
    scope = EXCLUDED.scope,
    risk_level = EXCLUDED.risk_level,
    mitigating_measures = EXCLUDED.mitigating_measures,
    owner = EXCLUDED.owner,
    review_due_at = EXCLUDED.review_due_at,
    is_active = EXCLUDED.is_active,
    updated_at = NOW()
RETURNING id, key, display_name, status, summary, scope, risk_level, mitigating_measures, owner, review_due_at, is_active, created_at, updated_at
`

type UpsertDPIARecordParams struct {
	Key                string             `json:"key"`
	DisplayName        string             `json:"display_name"`
	Status             string             `json:"status"`
	Summary            string             `json:"summary"`
	Scope              string             `json:"scope"`
	RiskLevel          string             `json:"risk_level"`
	MitigatingMeasures string             `json:"mitigating_measures"`
	Owner              string             `json:"owner"`
	ReviewDueAt        pgtype.Timestamptz `json:"review_due_at"`
	IsActive           bool               `json:"is_active"`
}

func (q *Queries) UpsertDPIARecord(ctx context.Context, arg UpsertDPIARecordParams) (DpiaRecord, error) {
	row := q.db.QueryRow(ctx, upsertDPIARecord,
		arg.Key,
		arg.DisplayName,
		arg.Status,
		arg.Summary,
		arg.Scope,
		arg.RiskLevel,
		arg.MitigatingMeasures,
		arg.Owner,
		arg.ReviewDueAt,
		arg.IsActive,
	)
	var i DpiaRecord
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.DisplayName,
		&i.Status,
		&i.Summary,
		&i.Scope,
		&i.RiskLevel,
		&i.MitigatingMeasures,
		&i.Owner,
		&i.ReviewDueAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProcessingActivity = `-- name: UpsertProcessingActivity :one
INSERT INTO processing_activities (
  key,
  display_name,
  purpose,
  legal_basis,
  data_subject_categories,
  personal_data_categories,
  recipient_categories,
  transfer_notes,
  retention_summary,
  security_measures,
  owner,
  is_active,
  updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, NOW())
ON CONFLICT (key) DO UPDATE
SET display_name = EXCLUDED.display_name,
    purpose = EXCLUDED.purpose,
    legal_basis = EXCLUDED.legal_basis,
    data_subject_categories = EXCLUDED.data_subject_categories,
    personal_data_categories = EXCLUDED.personal_data_categories,
    recipient_categories = EXCLUDED.recipient_categories,
    transfer_notes = EXCLUDED.transfer_notes,
    retention_summary = EXCLUDED.retention_summary,
    security_measures = EXCLUDED.security_measures,
    owner = EXCLUDED.owner,
    is_active = EXCLUDED.is_active,
    updated_at = NOW()
RETURNING id, key, display_name, purpose, legal_basis, data_subject_categories, personal_data_categories, recipient_categories, transfer_notes, retention_summary, security_measures, owner, is_active, created_at, updated_at
`

type UpsertProcessingActivityParams struct {
	Key                    string `json:"key"`
	DisplayName            string `json:"display_name"`
	Purpose                string `json:"purpose"`
	LegalBasis             string `json:"legal_basis"`
	DataSubjectCategories  string `json:"data_subject_categories"`
	PersonalDataCategories string `json:"personal_data_categories"`
	RecipientCategories    string `json:"recipient_categories"`
	TransferNotes          string `json:"transfer_notes"`
	RetentionSummary       string `json:"retention_summary"`
	SecurityMeasures       string `json:"security_measures"`
	Owner                  string `json:"owner"`
	IsActive               bool   `json:"is_active"`
}

func (q *Queries) UpsertProcessingActivity(ctx context.Context, arg UpsertProcessingActivityParams) (ProcessingActivity, error) {
	row := q.db.QueryRow(ctx, upsertProcessingActivity,
		arg.Key,
		arg.DisplayName,
		arg.Purpose,
		arg.LegalBasis,
		arg.DataSubjectCategories,
		arg.PersonalDataCategories,
		arg.RecipientCategories,
		arg.TransferNotes,
		arg.RetentionSummary,
		arg.SecurityMeasures,
		arg.Owner,
		arg.IsActive,
	)
	var i ProcessingActivity
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.DisplayName,
		&i.Purpose,
		&i.LegalBasis,
		&i.DataSubjectCategories,
		&i.PersonalDataCategories,
		&i.RecipientCategories,
		&i.TransferNotes,
		&i.RetentionSummary,
		&i.SecurityMeasures,
		&i.Owner,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProcessor = `-- name: UpsertProcessor :one
INSERT INTO processors (
  key,
  display_name,
  relationship_type,
  service_area,
  website_url,
  primary_country,
  data_location,
  transfer_mechanism,
  dpa_status,
  notes,
  is_active,
  updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW())
ON CONFLICT (key) DO UPDATE
SET display_name = EXCLUDED.display_name,
    relationship_type = EXCLUDED.relationship_type,
    service_area = EXCLUDED.service_area,
    website_url = EXCLUDED.website_url,
    primary_country = EXCLUDED.primary_country,
    data_location = EXCLUDED.data_location,
    transfer_mechanism = EXCLUDED.transfer_mechanism,
    dpa_status = EXCLUDED.dpa_status,
    notes = EXCLUDED.notes,
    is_active = EXCLUDED.is_active,
    updated_at = NOW()
RETURNING id, key, display_name, relationship_type, service_area, website_url, primary_country, data_location, transfer_mechanism, dpa_status, notes, is_active, created_at, updated_at
`

type UpsertProcessorParams struct {
	Key               string `json:"key"`
	DisplayName       string `json:"display_name"`
	RelationshipType  string `json:"relationship_type"`
	ServiceArea       string `json:"service_area"`
	WebsiteUrl        string `json:"website_url"`
	PrimaryCountry    string `json:"primary_country"`
	DataLocation      string `json:"data_location"`
	TransferMechanism string `json:"transfer_mechanism"`
	DpaStatus         string `json:"dpa_status"`
	Notes             string `json:"notes"`
	IsActive          bool   `json:"is_active"`
}

func (q *Queries) UpsertProcessor(ctx context.Context, arg UpsertProcessorParams) (Processor, error) {
	row := q.db.QueryRow(ctx, upsertProcessor,
		arg.Key,
		arg.DisplayName,
		arg.RelationshipType,
		arg.ServiceArea,
		arg.WebsiteUrl,
		arg.PrimaryCountry,
		arg.DataLocation,
		arg.TransferMechanism,
		arg.DpaStatus,
		arg.Notes,
		arg.IsActive,
	)
	var i Processor
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.DisplayName,
		&i.RelationshipType,
		&i.ServiceArea,
		&i.WebsiteUrl,
		&i.PrimaryCountry,
		&i.DataLocation,
		&i.TransferMechanism,
		&i.DpaStatus,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRetentionPolicy = `-- name: UpsertRetentionPolicy :one
INSERT INTO retention_policies (
  key,
  display_name,
  data_category,
  description,
  retention_days,
  trigger_event,
  storage_scope,
  deletion_method,
  legal_basis,
  notes,
  is_active,
  updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW())
ON CONFLICT (key) DO UPDATE
SET display_name = EXCLUDED.display_name,
    data_category = EXCLUDED.data_category,
    description = EXCLUDED.description,
    retention_days = EXCLUDED.retention_days,
    trigger_event = EXCLUDED.trigger_event,
    storage_scope = EXCLUDED.storage_scope,
    deletion_method = EXCLUDED.deletion_method,
    legal_basis = EXCLUDED.legal_basis,
    notes = EXCLUDED.notes,
    is_active = EXCLUDED.is_active,
    updated_at = NOW()
RETURNING id, key, display_name, data_category, description, retention_days, trigger_event, storage_scope, deletion_method, legal_basis, notes, is_active, created_at, updated_at
`

type UpsertRetentionPolicyParams struct {
	Key            string      `json:"key"`
	DisplayName    string      `json:"display_name"`
	DataCategory   string      `json:"data_category"`
	Description    string      `json:"description"`
	RetentionDays  pgtype.Int4 `json:"retention_days"`
	TriggerEvent   string      `json:"trigger_event"`
	StorageScope   string      `json:"storage_scope"`
	DeletionMethod string      `json:"deletion_method"`
	LegalBasis     string      `json:"legal_basis"`
	Notes          string      `json:"notes"`
	IsActive       bool        `json:"is_active"`
}

func (q *Queries) UpsertRetentionPolicy(ctx context.Context, arg UpsertRetentionPolicyParams) (RetentionPolicy, error) {
	row := q.db.QueryRow(ctx, upsertRetentionPolicy,
		arg.Key,
		arg.DisplayName,
		arg.DataCategory,
		arg.Description,
		arg.RetentionDays,
		arg.TriggerEvent,
		arg.StorageScope,
		arg.DeletionMethod,
		arg.LegalBasis,
		arg.Notes,
		arg.IsActive,
	)
	var i RetentionPolicy
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.DisplayName,
		&i.DataCategory,
		&i.Description,
		&i.RetentionDays,
		&i.TriggerEvent,
		&i.StorageScope,
		&i.DeletionMethod,
		&i.LegalBasis,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
