// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AcceptanceEvent struct {
	ID                string             `json:"id"`
	SubjectRef        string             `json:"subject_ref"`
	DocumentVersionID string             `json:"document_version_id"`
	AcceptedAt        pgtype.Timestamptz `json:"accepted_at"`
	SourceService     string             `json:"source_service"`
	SourceApp         string             `json:"source_app"`
	IpAddress         string             `json:"ip_address"`
	UserAgent         string             `json:"user_agent"`
	EvidenceSha256    string             `json:"evidence_sha256"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ConsentEvent struct {
	ID                string             `json:"id"`
	SubjectRef        string             `json:"subject_ref"`
	ConsentPurposeID  string             `json:"consent_purpose_id"`
	DocumentVersionID string             `json:"document_version_id"`
	Status            string             `json:"status"`
	LegalBasis        string             `json:"legal_basis"`
	ChangedAt         pgtype.Timestamptz `json:"changed_at"`
	SourceService     string             `json:"source_service"`
	SourceApp         string             `json:"source_app"`
	EvidenceSha256    string             `json:"evidence_sha256"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ConsentPurpose struct {
	ID          string             `json:"id"`
	Key         string             `json:"key"`
	DisplayName string             `json:"display_name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Document struct {
	ID          string             `json:"id"`
	Key         string             `json:"key"`
	DisplayName string             `json:"display_name"`
	Category    string             `json:"category"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type DocumentVersion struct {
	ID            string             `json:"id"`
	DocumentID    string             `json:"document_id"`
	Version       string             `json:"version"`
	Locale        string             `json:"locale"`
	Audience      string             `json:"audience"`
	ContentType   string             `json:"content_type"`
	ContentText   string             `json:"content_text"`
	ContentSha256 string             `json:"content_sha256"`
	IsPublished   bool               `json:"is_published"`
	EffectiveFrom pgtype.Timestamptz `json:"effective_from"`
	CreatedBy     string             `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
