// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AcceptanceEvent struct {
	ID                string             `json:"id"`
	SubjectRef        string             `json:"subject_ref"`
	DocumentVersionID string             `json:"document_version_id"`
	AcceptedAt        pgtype.Timestamptz `json:"accepted_at"`
	SourceService     string             `json:"source_service"`
	SourceApp         string             `json:"source_app"`
	IpAddress         string             `json:"ip_address"`
	UserAgent         string             `json:"user_agent"`
	EvidenceSha256    string             `json:"evidence_sha256"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ConsentEvent struct {
	ID                string             `json:"id"`
	SubjectRef        string             `json:"subject_ref"`
	ConsentPurposeID  string             `json:"consent_purpose_id"`
	DocumentVersionID string             `json:"document_version_id"`
	Status            string             `json:"status"`
	LegalBasis        string             `json:"legal_basis"`
	ChangedAt         pgtype.Timestamptz `json:"changed_at"`
	SourceService     string             `json:"source_service"`
	SourceApp         string             `json:"source_app"`
	EvidenceSha256    string             `json:"evidence_sha256"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ConsentPurpose struct {
	ID          string             `json:"id"`
	Key         string             `json:"key"`
	DisplayName string             `json:"display_name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Document struct {
	ID          string             `json:"id"`
	Key         string             `json:"key"`
	DisplayName string             `json:"display_name"`
	Category    string             `json:"category"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type DocumentVersion struct {
	ID            string             `json:"id"`
	DocumentID    string             `json:"document_id"`
	Version       string             `json:"version"`
	Locale        string             `json:"locale"`
	Audience      string             `json:"audience"`
	ContentType   string             `json:"content_type"`
	ContentText   string             `json:"content_text"`
	ContentSha256 string             `json:"content_sha256"`
	IsPublished   bool               `json:"is_published"`
	EffectiveFrom pgtype.Timestamptz `json:"effective_from"`
	CreatedBy     string             `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type DpiaRecord struct {
	ID                 string             `json:"id"`
	Key                string             `json:"key"`
	DisplayName        string             `json:"display_name"`
	Status             string             `json:"status"`
	Summary            string             `json:"summary"`
	Scope              string             `json:"scope"`
	RiskLevel          string             `json:"risk_level"`
	MitigatingMeasures string             `json:"mitigating_measures"`
	Owner              string             `json:"owner"`
	ReviewDueAt        pgtype.Timestamptz `json:"review_due_at"`
	IsActive           bool               `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ProcessingActivity struct {
	ID                     string             `json:"id"`
	Key                    string             `json:"key"`
	DisplayName            string             `json:"display_name"`
	Purpose                string             `json:"purpose"`
	LegalBasis             string             `json:"legal_basis"`
	DataSubjectCategories  string             `json:"data_subject_categories"`
	PersonalDataCategories string             `json:"personal_data_categories"`
	RecipientCategories    string             `json:"recipient_categories"`
	TransferNotes          string             `json:"transfer_notes"`
	RetentionSummary       string             `json:"retention_summary"`
	SecurityMeasures       string             `json:"security_measures"`
	Owner                  string             `json:"owner"`
	IsActive               bool               `json:"is_active"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type Processor struct {
	ID                string             `json:"id"`
	Key               string             `json:"key"`
	DisplayName       string             `json:"display_name"`
	RelationshipType  string             `json:"relationship_type"`
	ServiceArea       string             `json:"service_area"`
	WebsiteUrl        string             `json:"website_url"`
	PrimaryCountry    string             `json:"primary_country"`
	DataLocation      string             `json:"data_location"`
	TransferMechanism string             `json:"transfer_mechanism"`
	DpaStatus         string             `json:"dpa_status"`
	Notes             string             `json:"notes"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type RetentionPolicy struct {
	ID             string             `json:"id"`
	Key            string             `json:"key"`
	DisplayName    string             `json:"display_name"`
	DataCategory   string             `json:"data_category"`
	Description    string             `json:"description"`
	RetentionDays  pgtype.Int4        `json:"retention_days"`
	TriggerEvent   string             `json:"trigger_event"`
	StorageScope   string             `json:"storage_scope"`
	DeletionMethod string             `json:"deletion_method"`
	LegalBasis     string             `json:"legal_basis"`
	Notes          string             `json:"notes"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
